[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[program:core]
command=uv run python -u main.py
directory=/home/pi/ems/core
user=pi
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/tmp/ems_core.log
stderr_logfile=/tmp/ems_core.log

[program:fan]
command=uv run python -u main.py
directory=/home/pi/ems/fan
user=pi
autostart=true
autorestart=true
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/tmp/ems_fan.log
stderr_logfile=/tmp/ems_fan.log

[program:updater]
command=/bin/bash /home/pi/ems/update.sh
directory=/home/pi/ems
user=pi
autostart=true
autorestart=true
environment=UPDATE_INTERVAL="300"
stdout_logfile=/tmp/ems_updater.log
stderr_logfile=/tmp/ems_updater.log
